AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Description: Unique name for your bucket. This will be in the S3 url to your React app.
    Type: String

Resources:
  SuperAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  SuperAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SuperAppBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref SuperAppBucket, /*]]

  SuperAppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - POST
          ViewerProtocolPolicy: "redirect-to-https"
          TargetOriginId: SuperAppOrigin
        DefaultRootObject: index.html
        Enabled: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: index.html
            ResponseCode: 200
        Origins:
          - Id: SuperAppOrigin
            DomainName:
              !Join [
                "",
                "http://",
                !Ref BucketName,
                ".s3-website.us-east-2.amazonaws.com/",
              ]
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only

  SuperAppCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        !Join [
          "",
          ["http://", !Ref BucketName, ".s3-website.us-east-2.amazonaws.com/"],
        ]
      ValidationMethod: DNS
